let adminData={users:[],audit:[]},pendingAction=null;
const aid=id=>document.getElementById(id),safe=value=>String(value??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
async function invokeAdmin(action,payload={}){const client=LifeTagCloud.client();if(!client)throw new Error("Cloud is not configured.");const {data,error}=await client.functions.invoke("admin-api",{body:{action,...payload}});if(error)throw new Error(error.context?.body?await error.context.text():error.message);if(data?.error)throw new Error(data.error);return data;}
async function loadAdmin(){aid("adminGate").innerHTML="<h2>Verifying administrator access…</h2>";try{const data=await invokeAdmin("dashboard");adminData=data;aid("adminGate").hidden=true;aid("adminWorkspace").hidden=false;aid("adminIdentity").textContent=data.admin.email;aid("adminRole").textContent=data.admin.role.replaceAll("_"," ");aid("adminUsers").textContent=data.metrics.users;aid("adminProfiles").textContent=data.metrics.profiles;aid("adminNotifications").textContent=data.metrics.notifications;aid("adminDocuments").textContent=data.metrics.documents;renderUsers();renderAudit();aid("adminHealth").innerHTML=data.health.map(item=>`<div><span>${item.ok?"✓":"!"}</span>${safe(item.label)}</div>`).join("");}catch(error){aid("adminGate").innerHTML=`<h2>Access unavailable</h2><p>${safe(error.message)}</p><a class="button button-primary" href="auth.html">Open Secure Account</a>`;}}
function renderUsers(){const q=aid("adminSearch").value.toLowerCase();aid("adminAccountRows").innerHTML=adminData.users.filter(u=>`${u.email} ${u.id}`.toLowerCase().includes(q)).map(u=>`<tr><td><strong>${safe(u.email||"No email")}</strong><small>${safe(u.id)}</small></td><td>${safe(new Date(u.created_at).toLocaleDateString())}</td><td>${u.last_sign_in_at?safe(new Date(u.last_sign_in_at).toLocaleString()):"Never"}</td><td><span class="readiness-badge ${u.banned_until?"attention":"ready"}">${u.banned_until?"Suspended":"Active"}</span></td><td><button class="mini-danger" data-user-action="${u.banned_until?"restore":"suspend"}" data-user-id="${safe(u.id)}" data-email="${safe(u.email)}">${u.banned_until?"Restore":"Suspend"}</button></td></tr>`).join("");document.querySelectorAll("[data-user-action]").forEach(button=>button.onclick=()=>openAction(button.dataset.userAction,button.dataset.userId,button.dataset.email));}
function renderAudit(){aid("adminAuditList").innerHTML=adminData.audit.map(e=>`<article class="care-item"><div><strong>${safe(e.action)}</strong><small>${safe(new Date(e.created_at).toLocaleString())} · ${safe(e.actor_email||"System")}</small><p>${safe(e.metadata?.reason||"No reason recorded")}</p></div></article>`).join("")||'<div class="care-empty">No administrative events.</div>';}
function openAction(action,userId,email){pendingAction={action,userId};aid("adminActionTitle").textContent=action==="suspend"?"Suspend account":"Restore account";aid("adminActionText").textContent=`This will ${action} ${email}. The reason will be permanently audited.`;aid("adminReason").value="";aid("adminActionDialog").showModal();}
aid("adminActionForm").onsubmit=async event=>{event.preventDefault();try{await invokeAdmin("account_action",{operation:pendingAction.action,userId:pendingAction.userId,reason:aid("adminReason").value});aid("adminActionDialog").close();await loadAdmin();}catch(error){alert(error.message);}};
aid("cancelAdminAction").onclick=()=>aid("adminActionDialog").close();aid("adminSearch").oninput=renderUsers;aid("refreshAdmin").onclick=loadAdmin;
document.querySelectorAll("[data-admin-tab]").forEach(button=>button.onclick=()=>{document.querySelectorAll("[data-admin-tab],[data-admin-panel]").forEach(x=>x.classList.remove("active"));button.classList.add("active");document.querySelector(`[data-admin-panel="${button.dataset.adminTab}"]`).classList.add("active");});
window.addEventListener("load",()=>setTimeout(loadAdmin,600));
