const PROFILES_KEY = "lifetag_profiles_v3";
const THEME_KEY = "lifetag_theme_v3";
const byId = id => document.getElementById(id);
const PROFILE_FIELDS = ["fullName","birthdate","bloodType","sex","location","address","allergies","conditions","medications","notes","organDonor","preferredHospital","physicianName","physicianPhone","contactName","relationship","phone","altPhone","secondaryContactName","secondaryPhone","insuranceProvider","insurancePolicy","lastReviewed","preferredLanguage","accessibilityNeeds"];
const READINESS_FIELDS = ["fullName","birthdate","bloodType","allergies","conditions","medications","contactName","phone","address","lastReviewed"];

function getProfiles() { try { const data = JSON.parse(localStorage.getItem(PROFILES_KEY)); return Array.isArray(data) ? data : []; } catch { return []; } }
function saveProfiles(profiles) { localStorage.setItem(PROFILES_KEY, JSON.stringify(profiles)); window.LifeTagCloud?.enqueue("profiles",{count:profiles.length}); }
function createId() { return `${Date.now()}-${Math.random().toString(16).slice(2)}`; }
function clean(value, fallback = "—") { const text = String(value || "").trim(); return text || fallback; }
function escapeHTML(value) { return String(value ?? "").replace(/[&<>'"]/g, char => ({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[char])); }
function initials(name) { const parts = String(name || "").trim().split(/\s+/).filter(Boolean); return parts.length ? parts.slice(0,2).map(part => part[0]).join("").toUpperCase() : "LT"; }
function formatDate(value) { if (!value) return "—"; const date = new Date(`${value}T00:00:00`); return Number.isNaN(date.getTime()) ? "—" : date.toLocaleDateString(undefined,{year:"numeric",month:"long",day:"numeric"}); }
function ageFromDate(value) { if (!value) return ""; const birth = new Date(`${value}T00:00:00`); if (Number.isNaN(birth.getTime())) return ""; const today = new Date(); let age = today.getFullYear()-birth.getFullYear(); if (today.getMonth()<birth.getMonth() || (today.getMonth()===birth.getMonth() && today.getDate()<birth.getDate())) age--; return age >= 0 ? age : ""; }
function phoneLink(phone) { return String(phone || "").replace(/[^\d+]/g, ""); }
function getQueryId() { return new URLSearchParams(location.search).get("id"); }
function selectedProfile() { return getProfiles().find(profile => profile.id === getQueryId()) || null; }
function completeness(profile) { return Math.round(READINESS_FIELDS.filter(key => String(profile[key] || "").trim()).length / READINESS_FIELDS.length * 100); }
function isReviewOverdue(profile) { if (!profile.lastReviewed) return true; const date = new Date(`${profile.lastReviewed}T00:00:00`); return Number.isNaN(date.getTime()) || Date.now()-date.getTime() > 365*86400000; }
function readiness(profile) { const score = completeness(profile); const stale = isReviewOverdue(profile); return {score, stale, ready: score >= 80 && !stale}; }
function showMessage(title,text,icon="✓") { const dialog=byId("messageDialog"); if(!dialog){alert(`${title}\n\n${text}`);return;} byId("messageTitle").textContent=title; byId("messageText").textContent=text; byId("messageIcon").textContent=icon; dialog.showModal(); }

function applyTheme(theme) { document.body.classList.toggle("dark",theme==="dark"); const toggle=byId("themeToggle"); if(toggle){toggle.textContent=theme==="dark"?"☀":"◐";toggle.setAttribute("aria-label","Toggle color theme");} }
function toggleTheme(){const next=document.body.classList.contains("dark")?"light":"dark";localStorage.setItem(THEME_KEY,next);applyTheme(next);}
byId("themeToggle")?.addEventListener("click",toggleTheme); byId("settingsThemeToggle")?.addEventListener("click",toggleTheme); applyTheme(localStorage.getItem(THEME_KEY)||"light");

if(byId("profileCount")){const profiles=getProfiles();byId("profileCount").textContent=profiles.length;byId("readyCount").textContent=profiles.filter(p=>readiness(p).ready).length;byId("needsReviewCount").textContent=profiles.filter(p=>!readiness(p).ready).length;}

const form=byId("multiProfileForm");
if(form){const existing=selectedProfile();if(existing){PROFILE_FIELDS.concat("id").forEach(key=>{if(byId(key))byId(key).value=existing[key]||"";});byId("formPageTitle").textContent=`Update ${existing.fullName}`;}
 form.addEventListener("submit",event=>{event.preventDefault();const profile={id:byId("profileId").value||createId(),createdAt:existing?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()};PROFILE_FIELDS.forEach(key=>profile[key]=byId(key)?.value.trim()||"");const all=getProfiles();const index=all.findIndex(item=>item.id===profile.id);if(index>=0)all[index]=profile;else all.push(profile);saveProfiles(all);showMessage("Profile saved",`${profile.fullName}'s care profile is ready. Completeness: ${completeness(profile)}%.`);byId("profileId").value=profile.id;});
 byId("resetForm")?.addEventListener("click",()=>{form.reset();byId("profileId").value="";history.replaceState({},"","add-profile.html");byId("formPageTitle").textContent="Create a care profile";});}

function renderProfiles(){const grid=byId("profilesGrid");if(!grid)return;const query=(byId("profileSearch").value||"").trim().toLowerCase(),blood=byId("bloodFilter").value,status=byId("readinessFilter").value,sort=byId("profileSort").value;
 const profiles=getProfiles().filter(profile=>{const state=readiness(profile),haystack=PROFILE_FIELDS.map(key=>profile[key]).join(" ").toLowerCase();return haystack.includes(query)&&(!blood||profile.bloodType===blood)&&(!status||(status==="ready"&&state.ready)||(status==="incomplete"&&state.score<80)||(status==="stale"&&state.stale));}).sort((a,b)=>sort==="updated"?String(b.updatedAt||"").localeCompare(String(a.updatedAt||"")):sort==="completeness"?completeness(b)-completeness(a):String(a.fullName).localeCompare(String(b.fullName)));
 grid.innerHTML="";byId("visibleCount").textContent=profiles.length;byId("emptyState").hidden=profiles.length!==0;
 profiles.forEach(profile=>{const state=readiness(profile),card=document.createElement("article"),safeId=encodeURIComponent(profile.id);card.className="profile-card";card.innerHTML=`<div class="profile-card-top"><div class="avatar">${escapeHTML(initials(profile.fullName))}</div><div><h2>${escapeHTML(clean(profile.fullName))}</h2><p>${escapeHTML(clean(profile.location,"Location not provided"))}</p></div></div><div class="profile-card-info"><span><small>Blood Type</small><strong>${escapeHTML(clean(profile.bloodType))}</strong></span><span><small>Emergency Contact</small><strong>${escapeHTML(clean(profile.contactName))}</strong></span></div><div class="readiness-row"><span class="readiness-badge ${state.ready?"ready":"attention"}">${state.ready?"Emergency ready":`${state.score}% complete`}</span><small>${state.stale?"Review overdue":"Review current"}</small></div><div class="profile-card-actions"><a class="button button-primary" href="profile.html?id=${safeId}">View Profile</a><a class="button button-outline" href="emergency.html?id=${safeId}">Emergency</a><button class="button button-danger-ghost delete-profile-button" data-id="${escapeHTML(profile.id)}" type="button">Delete</button></div>`;grid.appendChild(card);});
 document.querySelectorAll(".delete-profile-button").forEach(button=>button.addEventListener("click",()=>{if(!confirm("Delete this profile permanently?"))return;saveProfiles(getProfiles().filter(profile=>profile.id!==button.dataset.id));renderProfiles();}));}
if(byId("profileSearch")){renderProfiles();["profileSearch","bloodFilter","readinessFilter","profileSort"].forEach(id=>byId(id).addEventListener(id==="profileSearch"?"input":"change",renderProfiles));byId("clearFilters").addEventListener("click",()=>{["profileSearch","bloodFilter","readinessFilter"].forEach(id=>byId(id).value="");byId("profileSort").value="name";renderProfiles();});}

if(byId("detailName")){const p=selectedProfile();if(p){const set=(id,value)=>byId(id).textContent=value;set("detailAvatar",initials(p.fullName));set("detailName",p.fullName);set("detailLocation",clean(p.location,"Location not provided"));set("detailBirthdate",formatDate(p.birthdate));set("detailBlood",clean(p.bloodType));set("detailSex",clean(p.sex));set("detailContact",clean(p.contactName));set("detailRelationship",clean(p.relationship));set("detailPhone",clean(p.phone));byId("detailPhone").href=p.phone?`tel:${phoneLink(p.phone)}`:"#";set("detailAllergies",clean(p.allergies,"No known allergies"));set("detailConditions",clean(p.conditions,"No known conditions"));set("detailMedications",clean(p.medications,"No information provided"));set("detailNotes",clean(p.notes,"No information provided"));set("detailPhysician",clean([p.physicianName,p.physicianPhone].filter(Boolean).join(" · ")));set("detailHospital",clean(p.preferredHospital));set("detailInsurance",clean([p.insuranceProvider,p.insurancePolicy].filter(Boolean).join(" · ")));set("detailCompleteness",`${completeness(p)}%`);byId("detailCompleteness").classList.add(readiness(p).ready?"ready":"attention");set("detailReviewed",`${formatDate(p.lastReviewed)}${isReviewOverdue(p)?" · Review recommended":" · Current"}`);set("detailAccessibility",clean([p.preferredLanguage,p.accessibilityNeeds].filter(Boolean).join(" · ")));byId("emergencyLink").href=`emergency.html?id=${encodeURIComponent(p.id)}`;byId("editLink").href=`add-profile.html?id=${encodeURIComponent(p.id)}`;byId("shareProfile").addEventListener("click",async()=>{const url=new URL(`emergency.html?id=${encodeURIComponent(p.id)}`,location.href).href;try{await navigator.clipboard.writeText(url);byId("shareProfile").textContent="Link Copied";}catch{prompt("Copy this emergency link:",url);}});}}

if(byId("emergencyName")){const p=selectedProfile();if(p){const set=(id,value)=>byId(id).textContent=value,age=ageFromDate(p.birthdate);set("emergencyName",p.fullName);set("emergencyBlood",clean(p.bloodType));set("emergencyBirthdate",age===""?formatDate(p.birthdate):`${formatDate(p.birthdate)} (${age} years old)`);set("emergencyAllergies",clean(p.allergies,"No known allergies"));set("emergencyConditions",clean(p.conditions,"No known conditions"));set("emergencyMedications",clean(p.medications,"No information provided"));set("emergencyNotes",clean(p.notes,"No information provided"));set("emergencyContact",clean(p.contactName,"No contact saved"));set("emergencyRelationship",clean(p.relationship));set("emergencyPhone",clean(p.phone));byId("emergencyPhoneLink").href=p.phone?`tel:${phoneLink(p.phone)}`:"#";set("emergencyLocation",p.address?`Saved address: ${p.address}`:p.location?`Home area: ${p.location}`:"");set("emergencyHospital",clean(p.preferredHospital));set("emergencyPhysician",clean([p.physicianName,p.physicianPhone].filter(Boolean).join(" · ")));set("emergencyAccessibility",clean([p.preferredLanguage,p.accessibilityNeeds].filter(Boolean).join(" · ")));byId("backProfile").href=`profile.html?id=${encodeURIComponent(p.id)}`;const address=p.address||p.location;if(address)byId("mapsLink").href=`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(address)}`;byId("copyEmergencySummary").addEventListener("click",async()=>{const summary=`${p.fullName}\nBlood: ${clean(p.bloodType)}\nAllergies: ${clean(p.allergies,"None known")}\nConditions: ${clean(p.conditions,"None known")}\nMedications: ${clean(p.medications,"Not provided")}\nEmergency contact: ${clean(p.contactName)} ${clean(p.phone,"")}`;try{await navigator.clipboard.writeText(summary);byId("copyEmergencySummary").querySelector("strong").textContent="Summary Copied";}catch{prompt("Copy emergency summary:",summary);}});}byId("printEmergency")?.addEventListener("click",()=>window.print());}

byId("exportAllProfiles")?.addEventListener("click",()=>{const profiles=getProfiles();if(!profiles.length){showMessage("No profiles","There are no profiles to export.","!");return;}let care={};try{care=JSON.parse(localStorage.getItem("lifetag_care_v1"))||{};}catch{}const blob=new Blob([JSON.stringify({version:5,profiles,care,exportedAt:new Date().toISOString()},null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=`lifetag-complete-backup-${new Date().toISOString().slice(0,10)}.json`;link.click();URL.revokeObjectURL(url);});
byId("importAllProfiles")?.addEventListener("change",event=>{const file=event.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(reader.result),imported=Array.isArray(data)?data:data.profiles;if(!Array.isArray(imported))throw new Error();saveProfiles(imported);if(data.care&&typeof data.care==="object")localStorage.setItem("lifetag_care_v1",JSON.stringify(data.care));showMessage("Backup imported",`${imported.length} profiles and their available care records were restored.`);}catch{showMessage("Invalid backup","The selected file is not a valid LifeTag backup.","!");}event.target.value="";};reader.readAsText(file);});

if(byId("careLink")&&selectedProfile())byId("careLink").href=`care.html?id=${encodeURIComponent(selectedProfile().id)}`;
if(byId("emergencyActionPlans")&&selectedProfile()){try{const care=JSON.parse(localStorage.getItem("lifetag_care_v1"))||{},plans=care[selectedProfile().id]?.plans||[];if(plans.length){byId("emergencyActionPlans").hidden=false;byId("emergencyActionPlanList").innerHTML=plans.map(plan=>`<article><strong>${escapeHTML(plan.condition)}</strong><p><b>Warning signs:</b> ${escapeHTML(plan.warning)}</p><p><b>Immediate steps:</b> ${escapeHTML(plan.steps)}</p>${plan.rescue?`<p><b>Rescue medication/equipment:</b> ${escapeHTML(plan.rescue)}</p>`:""}</article>`).join("");}}catch{}}
if("serviceWorker" in navigator&&location.protocol!=="file:")navigator.serviceWorker.register("sw.js");

if(!window.LifeTagCloud){const sdk=document.createElement("script");sdk.src="https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2";sdk.onload=()=>{const cloud=document.createElement("script");cloud.src="backend.js";document.head.appendChild(cloud);};document.head.appendChild(sdk);}
byId("clearAllProfiles")?.addEventListener("click",()=>{if(!confirm("Delete all profiles and their care records from this browser?"))return;localStorage.removeItem(PROFILES_KEY);localStorage.removeItem("lifetag_care_v1");showMessage("All data deleted","The profile directory and care records are now empty.","×");});
