const message=(text,error=false)=>{const el=document.getElementById("authMessage");el.textContent=text;el.classList.toggle("error",error);};
async function refreshAuth(){const configured=LifeTagCloud.configured();document.getElementById("setupPanel").hidden=configured;document.getElementById("authPanel").hidden=!configured;document.getElementById("accountPanel").hidden=true;if(!configured)return;await new Promise(resolve=>setTimeout(resolve,300));const user=LifeTagCloud.user();if(user){document.getElementById("authPanel").hidden=true;document.getElementById("accountPanel").hidden=false;document.getElementById("accountEmail").textContent=user.email;}}
document.getElementById("cloudSetupForm").addEventListener("submit",event=>{event.preventDefault();const url=document.getElementById("supabaseUrl").value.trim(),anonKey=document.getElementById("supabaseAnonKey").value.trim();if(!url.includes(".supabase.co"))return message("Enter a valid Supabase project URL.",true);LifeTagCloud.setConfig({url,anonKey});});
document.getElementById("authForm").addEventListener("submit",async event=>{event.preventDefault();const {error}=await LifeTagCloud.client().auth.signInWithPassword({email:document.getElementById("authEmail").value,password:document.getElementById("authPassword").value});if(error)return message(error.message,true);message("Signed in. Synchronizing…");await LifeTagCloud.pull();await LifeTagCloud.flush();refreshAuth();});
document.getElementById("createAccount").addEventListener("click",async()=>{const email=document.getElementById("authEmail").value,password=document.getElementById("authPassword").value;if(!email||password.length<8)return message("Enter an email and a password of at least 8 characters.",true);const {error}=await LifeTagCloud.client().auth.signUp({email,password});message(error?error.message:"Check your email to confirm the new account.",Boolean(error));});
document.getElementById("resetPassword").addEventListener("click",async()=>{const email=document.getElementById("authEmail").value;if(!email)return message("Enter your email first.",true);const {error}=await LifeTagCloud.client().auth.resetPasswordForEmail(email,{redirectTo:location.href});message(error?error.message:"Password reset email sent.",Boolean(error));});
document.getElementById("syncNow").addEventListener("click",async()=>{await LifeTagCloud.pull();await LifeTagCloud.flush();message("Cloud synchronization complete.");});
document.getElementById("signOut").addEventListener("click",async()=>{await LifeTagCloud.client().auth.signOut();refreshAuth();});
document.getElementById("disconnectCloud").addEventListener("click",()=>{if(confirm("Disconnect Supabase from this browser? Offline data will remain."))LifeTagCloud.clearConfig();});
window.addEventListener("load",()=>setTimeout(refreshAuth,450));
