(function(){
  const CONFIG_KEY="lifetag_supabase_config", QUEUE_KEY="lifetag_sync_queue";
  let client=null,user=null,syncing=false;
  const config=()=>{try{return JSON.parse(localStorage.getItem(CONFIG_KEY))||{};}catch{return {};}};
  function configured(){const c=config();return Boolean(c.url&&c.anonKey&&window.supabase);}
  async function init(){if(client)return;if(!configured())return setStatus("local");const c=config();client=window.supabase.createClient(c.url,c.anonKey,{auth:{persistSession:true,autoRefreshToken:true}});const {data,error}=await client.auth.getSession();if(error){console.error("LifeTag session",error);setStatus("error");return;}user=data.session?.user||null;client.auth.onAuthStateChange((_event,session)=>{user=session?.user||null;setStatus(user?"online":"signed-out");});if(user){await pull();await flush();setStatus("online");}else setStatus("signed-out");}
  function setStatus(state){document.documentElement.dataset.cloud=state;document.querySelectorAll("[data-cloud-status]").forEach(el=>{el.textContent={online:"Cloud synced",syncing:"Syncing…",local:"Offline/local",queued:"Changes queued",error:"Cloud connection error","signed-out":"Sign in to sync"}[state]||state;});}
  function enqueue(kind,payload){const q=JSON.parse(localStorage.getItem(QUEUE_KEY)||"[]");q.push({id:crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`,kind,payload,at:new Date().toISOString()});localStorage.setItem(QUEUE_KEY,JSON.stringify(q));setStatus(navigator.onLine?"syncing":"queued");flush();}
  async function pushProfiles(){if(!user)return;const profiles=JSON.parse(localStorage.getItem("lifetag_profiles_v3")||"[]");if(!profiles.length)return;const rows=profiles.map(p=>({id:p.id,owner_id:user.id,data:p,updated_at:p.updatedAt||new Date().toISOString()}));const {error}=await client.from("health_profiles").upsert(rows,{onConflict:"id"});if(error)throw error;}
  async function pushCare(){if(!user)return;const care=JSON.parse(localStorage.getItem("lifetag_care_v1")||"{}");const typeMap={medications:"medication",appointments:"appointment",timeline:"timeline",vitals:"vital",plans:"action_plan",caregivers:"caregiver"},rows=[];Object.entries(care).forEach(([profileId,group])=>Object.entries(typeMap).forEach(([key,type])=>(group[key]||[]).forEach(item=>rows.push({profile_id:profileId,owner_id:user.id,record_type:type,client_id:item.id,data:item,occurred_at:item.date||item.createdAt||null}))));if(rows.length){const {error}=await client.from("care_records").upsert(rows,{onConflict:"profile_id,record_type,client_id"});if(error)throw error;}}
  async function flush(){if(syncing||!client||!user||!navigator.onLine)return;syncing=true;setStatus("syncing");try{await pushProfiles();await pushCare();localStorage.removeItem(QUEUE_KEY);localStorage.removeItem("lifetag_sync_error");setStatus("online");}catch(error){console.error("LifeTag sync",error);localStorage.setItem("lifetag_sync_error",error?.message||String(error));setStatus("error");}finally{syncing=false;}}
  async function pull(){if(!client||!user)return;const [{data:profiles,error:pErr},{data:records,error:rErr}]=await Promise.all([client.from("health_profiles").select("data").is("deleted_at",null),client.from("care_records").select("profile_id,record_type,data").is("deleted_at",null)]);if(pErr||rErr)return;const local=JSON.parse(localStorage.getItem("lifetag_profiles_v3")||"[]"),merged=new Map(local.map(p=>[p.id,p]));(profiles||[]).forEach(row=>merged.set(row.data.id,row.data));localStorage.setItem("lifetag_profiles_v3",JSON.stringify([...merged.values()]));const care=JSON.parse(localStorage.getItem("lifetag_care_v1")||"{}"),reverse={medication:"medications",appointment:"appointments",timeline:"timeline",vital:"vitals",action_plan:"plans",caregiver:"caregivers"};(records||[]).forEach(row=>{care[row.profile_id]||={medications:[],appointments:[],timeline:[],documents:[],vitals:[],plans:[],caregivers:[]};const key=reverse[row.record_type];if(key&&!care[row.profile_id][key].some(x=>x.id===row.data.id))care[row.profile_id][key].push(row.data);});localStorage.setItem("lifetag_care_v1",JSON.stringify(care));}
  async function uploadDocument(profileId,file,title){if(!client||!user)throw new Error("Sign in to use secure document storage.");const safe=file.name.replace(/[^a-zA-Z0-9._-]/g,"_"),path=`${user.id}/${profileId}/${crypto.randomUUID()}-${safe}`;const {error}=await client.storage.from("health-documents").upload(path,file);if(error)throw error;const {error:metaError}=await client.from("health_documents").insert({profile_id:profileId,owner_id:user.id,title,storage_path:path,mime_type:file.type,size_bytes:file.size});if(metaError)throw metaError;return path;}
  async function audit(action,profileId,metadata={}){if(client&&user)await client.from("audit_events").insert({actor_id:user.id,profile_id:profileId,action,metadata});}
  window.LifeTagCloud={init,configured,config,user:()=>user,client:()=>client,enqueue,flush,pull,uploadDocument,audit,setConfig(c){localStorage.setItem(CONFIG_KEY,JSON.stringify(c));location.reload();},clearConfig(){localStorage.removeItem(CONFIG_KEY);location.reload();}};
  window.addEventListener("online",flush);if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init,{once:true});else init();
})();
