const CARE_KEY="lifetag_care_v1";
const careProfile=selectedProfile();
function getCare(){try{return JSON.parse(localStorage.getItem(CARE_KEY))||{};}catch{return {};}}
function saveCare(data){localStorage.setItem(CARE_KEY,JSON.stringify(data));window.LifeTagCloud?.enqueue("care",{profileId:getQueryId()});}
function profileCare(){const all=getCare();if(!all[getQueryId()])all[getQueryId()]={medications:[],appointments:[],timeline:[],documents:[],vitals:[],plans:[],caregivers:[]};return {all,data:all[getQueryId()]};}
function uid(){return `${Date.now()}-${Math.random().toString(16).slice(2)}`;}
function removeItem(type,id){const {all,data}=profileCare();data[type]=data[type].filter(item=>item.id!==id);saveCare(all);renderAll();}
function addItem(type,item){const {all,data}=profileCare();data[type].push({id:uid(),createdAt:new Date().toISOString(),...item});saveCare(all);renderAll();}
function card(title,meta,body,type,id,actions=""){return `<article class="care-item"><div><strong>${escapeHTML(title)}</strong><small>${escapeHTML(meta)}</small>${body?`<p>${escapeHTML(body)}</p>`:""}</div><div class="care-item-actions">${actions}<button class="mini-danger" data-remove="${type}" data-id="${escapeHTML(id)}" type="button">Remove</button></div></article>`;}
function localDate(value){if(!value)return "Not scheduled";const d=new Date(value);return Number.isNaN(d.getTime())?value:d.toLocaleString(undefined,{dateStyle:"medium",timeStyle:value.includes("T")?"short":undefined});}
function bindForm(id,callback){byId(id)?.addEventListener("submit",event=>{event.preventDefault();callback();event.target.reset();});}

if(!careProfile){document.querySelectorAll(".care-panel,.care-tabs").forEach(node=>node.hidden=true);}else{byId("careProfileName").textContent=`${careProfile.fullName}'s care plan`;byId("careProfileMeta").textContent="Medications, appointments, health history, monitoring, and shared care.";byId("careBackLink").href=`profile.html?id=${encodeURIComponent(careProfile.id)}`;}

document.querySelectorAll(".care-tabs button").forEach(button=>button.addEventListener("click",()=>{document.querySelectorAll(".care-tabs button,.care-panel").forEach(node=>node.classList.remove("active"));button.classList.add("active");document.querySelector(`[data-panel="${button.dataset.tab}"]`).classList.add("active");}));

bindForm("medicationForm",()=>addItem("medications",{name:byId("medName").value,dose:byId("medDose").value,schedule:byId("medSchedule").value,refill:byId("medRefill").value,instructions:byId("medInstructions").value,active:true}));
bindForm("appointmentForm",()=>addItem("appointments",{title:byId("appointmentTitle").value,date:byId("appointmentDate").value,provider:byId("appointmentProvider").value,location:byId("appointmentLocation").value,notes:byId("appointmentNotes").value}));
bindForm("timelineForm",()=>addItem("timeline",{title:byId("eventTitle").value,date:byId("eventDate").value,details:byId("eventDetails").value}));
bindForm("vitalForm",()=>addItem("vitals",{date:new Date().toISOString(),bp:byId("vitalBp").value,heart:byId("vitalHeart").value,spo2:byId("vitalSpo2").value,temp:byId("vitalTemp").value,glucose:byId("vitalGlucose").value,weight:byId("vitalWeight").value}));
bindForm("actionPlanForm",()=>addItem("plans",{condition:byId("planCondition").value,warning:byId("planWarning").value,steps:byId("planSteps").value,rescue:byId("planRescue").value}));
bindForm("caregiverForm",()=>addItem("caregivers",{name:byId("caregiverName").value,contact:byId("caregiverContact").value,role:byId("caregiverRole").value,expiry:byId("caregiverExpiry").value}));

byId("documentForm")?.addEventListener("submit",async event=>{event.preventDefault();const file=byId("documentFile").files[0],title=byId("documentTitle").value;if(!file)return;if(window.LifeTagCloud?.user()){try{const path=await LifeTagCloud.uploadDocument(getQueryId(),file,title);addItem("documents",{title,name:file.name,type:file.type,size:file.size,cloud:true,path});showMessage("Document secured","The file was uploaded to private cloud storage.");event.target.reset();return;}catch(error){showMessage("Upload failed",error.message,"!");return;}}if(file.size>1024*1024){showMessage("File too large","Offline files must be smaller than 1 MB. Sign in for secure cloud storage up to 10 MB.","!");return;}const reader=new FileReader();reader.onload=()=>{addItem("documents",{title,name:file.name,type:file.type,size:file.size,data:reader.result});event.target.reset();};reader.readAsDataURL(file);});

function vitalStatus(v){if(!v)return "No data";const flags=[];const spo2=Number(v.spo2),temp=Number(v.temp),heart=Number(v.heart);if(spo2&&spo2<95)flags.push("Low SpO₂");if(temp&&temp>=38)flags.push("High temperature");if(heart&&(heart<50||heart>120))flags.push("Heart rate check");return flags.length?flags.join(", "):"Recorded";}
function renderAll(){if(!careProfile)return;const {data}=profileCare(),now=Date.now();
 byId("medicationList").innerHTML=data.medications.length?data.medications.map(m=>card(m.name,[m.dose,m.schedule].filter(Boolean).join(" · "),m.instructions,"medications",m.id)).join(""):'<div class="care-empty">No medications recorded.</div>';
 byId("todayMedications").innerHTML=data.medications.length?data.medications.map(m=>`<div class="compact-row"><strong>${escapeHTML(m.name)}</strong><span>${escapeHTML(m.schedule||"Schedule not set")}</span></div>`).join(""):'<div class="care-empty">No medication schedule.</div>';
 const appointments=[...data.appointments].sort((a,b)=>new Date(a.date)-new Date(b.date));byId("appointmentList").innerHTML=appointments.length?appointments.map(a=>card(a.title,`${localDate(a.date)} · ${a.provider||"Provider not set"}`,`${a.location||""} ${a.notes||""}`.trim(),"appointments",a.id)).join(""):'<div class="care-empty">No appointments scheduled.</div>';
 const next=appointments.find(a=>new Date(a.date).getTime()>=now);byId("nextAppointment").innerHTML=next?`<strong>${escapeHTML(next.title)}</strong><p>${escapeHTML(localDate(next.date))}</p>`:"No upcoming appointment.";
 byId("timelineList").innerHTML=[...data.timeline].sort((a,b)=>String(b.date).localeCompare(String(a.date))).map(e=>`<article class="timeline-entry"><time>${escapeHTML(formatDate(e.date))}</time><div><strong>${escapeHTML(e.title)}</strong><p>${escapeHTML(e.details||"")}</p></div><button class="mini-danger" data-remove="timeline" data-id="${escapeHTML(e.id)}">Remove</button></article>`).join("")||'<div class="care-empty">No health events yet.</div>';
 byId("documentList").innerHTML=data.documents.map(d=>card(d.title,`${d.name} · ${Math.ceil(d.size/1024)} KB`,"Stored locally","documents",d.id,`<a class="mini-link" href="${d.data}" download="${escapeHTML(d.name)}">Open</a>`)).join("")||'<div class="care-empty">No documents stored.</div>';
 byId("vitalList").innerHTML=[...data.vitals].reverse().map(v=>card(localDate(v.date),`Status: ${vitalStatus(v)}`,[v.bp&&`BP ${v.bp}`,v.heart&&`HR ${v.heart}`,v.spo2&&`SpO₂ ${v.spo2}%`,v.temp&&`${v.temp} °C`,v.glucose&&`Glucose ${v.glucose}`,v.weight&&`${v.weight} kg`].filter(Boolean).join(" · "),"vitals",v.id)).join("")||'<div class="care-empty">No vital readings.</div>';
 byId("actionPlanList").innerHTML=data.plans.map(p=>card(p.condition,`Warning signs: ${p.warning}`,`Steps: ${p.steps}${p.rescue?` · Rescue: ${p.rescue}`:""}`,"plans",p.id)).join("")||'<div class="care-empty">No condition-specific plans.</div>';
 byId("caregiverList").innerHTML=data.caregivers.map(c=>card(c.name,`${c.role} · ${c.contact}`,c.expiry?`Expires ${formatDate(c.expiry)}`:"No expiry","caregivers",c.id)).join("")||'<div class="care-empty">No caregiver permissions recorded.</div>';
 byId("metricMedications").textContent=data.medications.length;byId("metricAppointments").textContent=appointments.filter(a=>new Date(a.date)>=new Date()).length;byId("metricDocuments").textContent=data.documents.length;byId("metricVitals").textContent=vitalStatus(data.vitals.at(-1));byId("medicationCount").textContent=`${data.medications.length} active`;
 const tasks=[];if(!data.medications.length)tasks.push("Confirm the current medication list");if(!data.plans.length&&careProfile.conditions)tasks.push("Create an action plan for known conditions");if(!data.caregivers.length)tasks.push("Assign a trusted caregiver");if(!data.documents.length)tasks.push("Store a recent prescription or clinical summary");byId("readinessTasks").innerHTML=tasks.length?tasks.map(t=>`<div><span>○</span>${escapeHTML(t)}</div>`):"All recommended care tasks are complete.";
 document.querySelectorAll("[data-remove]").forEach(button=>button.addEventListener("click",()=>{if(confirm("Remove this item?"))removeItem(button.dataset.remove,button.dataset.id);}));}

byId("enableReminders")?.addEventListener("click",async()=>{if(!("Notification" in window)){showMessage("Reminders unavailable","This browser does not support notifications.","!");return;}const result=await Notification.requestPermission();showMessage(result==="granted"?"Reminders enabled":"Permission not granted",result==="granted"?"LifeTag can now display medication and appointment reminders while the app is open.":"You can enable notifications later in browser settings.");});
byId("createTemporaryLink")?.addEventListener("click",async()=>{const expires=Date.now()+86400000,url=new URL(`profile.html?id=${encodeURIComponent(careProfile.id)}&access=viewer&expires=${expires}`,location.href).href;try{await navigator.clipboard.writeText(url);showMessage("24-hour link copied","The viewer link has been copied. Remote enforcement requires the production backend.");}catch{prompt("Copy temporary link:",url);}});
byId("downloadCalendar")?.addEventListener("click",()=>{const {data}=profileCare();if(!data.appointments.length){showMessage("No appointments","Schedule an appointment before exporting.","!");return;}const pad=n=>String(n).padStart(2,"0"),stamp=value=>{const d=new Date(value);return `${d.getUTCFullYear()}${pad(d.getUTCMonth()+1)}${pad(d.getUTCDate())}T${pad(d.getUTCHours())}${pad(d.getUTCMinutes())}00Z`;};const ics=["BEGIN:VCALENDAR","VERSION:2.0","PRODID:-//LifeTag//Care Plan//EN",...data.appointments.flatMap(a=>["BEGIN:VEVENT",`UID:${a.id}@lifetag`,`DTSTART:${stamp(a.date)}`,`SUMMARY:${a.title.replace(/[,;]/g," ")}`,`LOCATION:${(a.location||"").replace(/[,;]/g," ")}`,"END:VEVENT"]),"END:VCALENDAR"].join("\r\n"),blob=new Blob([ics],{type:"text/calendar"}),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=`${careProfile.fullName}-appointments.ics`;link.click();URL.revokeObjectURL(url);});

if("serviceWorker" in navigator&&location.protocol!=="file:")navigator.serviceWorker.register("sw.js");
renderAll();
